font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0
font_scale 2.0

window_padding_width 0

$foreground = {{colors.on_background.default.hex_stripped}}

background #181825

$primary = {{colors.primary.default.hex_stripped}}
$secondary = {{colors.secondary.default.hex_stripped}}
$tertiary = {{colors.tertiary.default.hex_stripped}}
$surface = {{colors.surface.default.hex_stripped}}
$surface_bright = {{colors.surface_bright.default.hex_stripped}}
$outline = {{colors.outline.default.hex_stripped}}
$error = {{colors.error.default.hex_stripped | set_lightness: -20.0}}

$shadow = {{colors.shadow.default.hex_stripped}}

$red = {{colors.red.default.hex_stripped}}
$green = {{colors.green.default.hex_stripped}}
$yellow = {{colors.yellow.default.hex_stripped}}
$blue = {{colors.blue.default.hex_stripped}}
$magenta = {{colors.magenta.default.hex_stripped}}
$cyan = {{colors.cyan.default.hex_stripped}}
$white = {{colors.white.default.hex_stripped}}
$red_dim = {{colors.red.default.hex_stripped | set_lightness: -20.0}}
$green_dim = {{colors.green.default.hex_stripped | set_lightness: -20.0}}
$yellow_dim = {{colors.yellow.default.hex_stripped | set_lightness: -20.0}}
$blue_dim = {{colors.blue.default.hex_stripped | set_lightness: -20.0}}
$magenta_dim = {{colors.magenta.default.hex_stripped | set_lightness: -20.0}}
$cyan_dim = {{colors.cyan.default.hex_stripped | set_lightness: -20.0}}

foreground #f2cdcd
background #181825

background_opacity 1
selection_foreground #11111b
selection_background #f2cdcd

# Black
color0 #0b0c15
# Red
color1 #d2556c
# Green
color2 #7cd47b
# Yellow
color3 #efb184
# Blue
color4 #6ca1f3
# Magenta
color5 #b78df0
# Cyan
color6 #69bcf4
# White
color7 #c0caf5

# Bright Black
color8  #39404a
# Bright Red
color9  #f7768e
# Bright Green
color10 #85e89d
# Bright Yellow
color11 #f4cf8d
# Bright Blue
color12 #8fb9ff
# Bright Magenta
color13 #d9a3ff
# Bright Cyan
color14 #8fd3ff
# Bright White
color15 #f0f3f6

#: The color table {{{

#: The 256 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version, for the first 16 colors. You can set the
#: remaining 240 colors as color16 to color255.

# color0 #000000
# color8 #767676

#: black

# color1 #cc0403
# color9 #f2201f

#: red

# color2  #19cb00
# color10 #23fd00

#: green

# color3  #cecb00
# color11 #fffd00

#: yellow

# color4  #0d73cc
# color12 #1a8fff

#: blue

# color5  #cb1ed1
# color13 #fd28ff

#: magenta

# color6  #0dcdcd
# color14 #14ffff

#: cyan

# color7  #dddddd
# color15 #ffffff

#: white

# mark1_foreground black

#: Color for marks of type 1

# mark1_background #98d3cb

#: Color for marks of type 1 (light steel blue)

# mark2_foreground black

#: Color for marks of type 2

# mark2_background #f2dcd3

#: Color for marks of type 1 (beige)

# mark3_foreground black

#: Color for marks of type 3

# mark3_background #f274bc

#: Color for marks of type 3 (violet)

#: }}}

